//
//  YouTubeCaptions.swift
//  MeetingMindKit
//
// Turns a YouTube link into a timed transcript from the video's own captions, so a talk or a
// lecture can be summarized like a meeting without downloading any audio.
//
// YouTube has no public captions API. This asks the player endpoint YouTube's Android app uses
// (the web page's caption links now come back empty without a browser proof-of-origin token),
// so it can stop working whenever YouTube changes it; failures say so plainly.

import Foundation

public enum YouTubeCaptions {
    public struct Video: Equatable, Sendable {
        public let id: String
        public let title: String
        public let pieces: [TranscriptPiece]

        /// The link saved on the note.
        public var watchURL: URL { URL(string: "https://www.youtube.com/watch?v=\(id)")! }
    }

    struct Track: Equatable {
        let baseURL: URL
        let languageCode: String
        let isAutoGenerated: Bool
    }

    public enum Failure: Error, LocalizedError, Equatable {
        case notYouTube
        case unavailable(reason: String?)
        case noCaptions
        case busy

        public var errorDescription: String? {
            switch self {
            case .notYouTube: "That doesn't look like a YouTube video link."
            case let .unavailable(reason): "YouTube wouldn't share this video" + (reason.map { ": \($0)" } ?? ".")
            case .noCaptions: "YouTube didn't share captions for this video, so there's nothing to transcribe."
            case .busy: "YouTube is turning away requests from this network for now. Try again in a few minutes."
            }
        }
    }

    // MARK: - Fetching

    public static func fetch(
        _ link: String,
        preferredLanguages: [String] = Locale.preferredLanguages,
        session: URLSession = .shared
    ) async throws -> Video {
        guard let id = videoID(from: link) else { throw Failure.notYouTube }
        let (playerData, playerResponse) = try await session.data(for: playerRequest(videoID: id))
        try check(playerResponse)
        let (title, tracks) = try player(from: playerData)
        guard let track = bestTrack(tracks, preferredLanguages: preferredLanguages) else { throw Failure.noCaptions }
        let (captionData, captionResponse) = try await session.data(from: json3URL(for: track))
        try check(captionResponse)
        let pieces = try Self.pieces(fromJSON3: captionData)
        guard !pieces.isEmpty else { throw Failure.noCaptions }
        return Video(id: id, title: title, pieces: pieces)
    }

    static func playerRequest(videoID: String) -> URLRequest {
        var request = URLRequest(url: URL(string: "https://www.youtube.com/youtubei/v1/player")!)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        let body: [String: Any] = [
            "context": ["client": ["clientName": "ANDROID", "clientVersion": "20.10.38"]],
            "videoId": videoID,
        ]
        request.httpBody = try? JSONSerialization.data(withJSONObject: body)
        return request
    }

    /// YouTube answers too many requests with an HTML "Sorry" page, which would otherwise surface as
    /// a baffling JSON error.
    static func check(_ response: URLResponse) throws {
        guard let status = (response as? HTTPURLResponse)?.statusCode, !(200..<300).contains(status) else { return }
        throw status == 429 ? Failure.busy : Failure.unavailable(reason: nil)
    }

    // MARK: - Parsing

    private static let hosts: Set<String> = [
        "youtube.com", "www.youtube.com", "m.youtube.com", "music.youtube.com", "youtube-nocookie.com",
        "www.youtube-nocookie.com",
    ]

    /// The 11-character video id from any of the link shapes YouTube shares: watch, youtu.be,
    /// shorts, embed and live. Pasted links often come without the scheme, so that's optional.
    public static func videoID(from link: String) -> String? {
        var text = link.trimmingCharacters(in: .whitespacesAndNewlines)
        if !text.contains("://") { text = "https://" + text }
        guard let components = URLComponents(string: text), let host = components.host?.lowercased() else { return nil }
        let parts = components.path.split(separator: "/").map(String.init)

        let candidate: String?
        if host == "youtu.be" {
            candidate = parts.first
        } else if hosts.contains(host) {
            if parts.first == "watch" {
                candidate = components.queryItems?.first { $0.name == "v" }?.value
            } else if parts.count >= 2, ["shorts", "embed", "live", "v"].contains(parts[0]) {
                candidate = parts[1]
            } else {
                candidate = nil
            }
        } else {
            candidate = nil
        }
        guard let id = candidate, id.count == 11,
              id.allSatisfy({ $0.isASCII && ($0.isLetter || $0.isNumber || $0 == "-" || $0 == "_") }) else { return nil }
        return id
    }

    private struct PlayerResponse: Decodable {
        struct Status: Decodable { let status: String?; let reason: String? }
        struct Details: Decodable { let title: String? }
        struct Captions: Decodable { let playerCaptionsTracklistRenderer: Renderer? }
        struct Renderer: Decodable { let captionTracks: [RawTrack]? }
        struct RawTrack: Decodable { let baseUrl: String; let languageCode: String; let kind: String? }

        let playabilityStatus: Status?
        let videoDetails: Details?
        let captions: Captions?
    }

    static func player(from data: Data) throws -> (title: String, tracks: [Track]) {
        let response = try JSONDecoder().decode(PlayerResponse.self, from: data)
        if let status = response.playabilityStatus, status.status != "OK" {
            throw Failure.unavailable(reason: status.reason)
        }
        let tracks = (response.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? []).compactMap { raw in
            URL(string: raw.baseUrl).map { Track(baseURL: $0, languageCode: raw.languageCode, isAutoGenerated: raw.kind == "asr") }
        }
        return (response.videoDetails?.title ?? "YouTube video", tracks)
    }

    /// Captions someone wrote beat YouTube's automatic ones, and the reader's own languages come
    /// first, in the order they're set. Failing both, the video's first track.
    static func bestTrack(_ tracks: [Track], preferredLanguages: [String]) -> Track? {
        func base(_ code: String) -> String { code.split(separator: "-").first.map { String($0).lowercased() } ?? "" }
        for automatic in [false, true] {
            for language in preferredLanguages {
                if let match = tracks.first(where: { $0.isAutoGenerated == automatic && base($0.languageCode) == base(language) }) {
                    return match
                }
            }
        }
        return tracks.first { !$0.isAutoGenerated } ?? tracks.first
    }

    static func json3URL(for track: Track) -> URL {
        var components = URLComponents(url: track.baseURL, resolvingAgainstBaseURL: false)!
        components.queryItems = (components.queryItems ?? []).filter { $0.name != "fmt" } + [URLQueryItem(name: "fmt", value: "json3")]
        return components.url!
    }

    private struct JSON3: Decodable {
        struct Event: Decodable { let tStartMs: Double?; let dDurationMs: Double?; let segs: [Segment]? }
        struct Segment: Decodable { let utf8: String? }
        let events: [Event]?
    }

    /// One piece per caption event. Automatic captions roll, so each one is cut off where the
    /// next begins rather than overlapping it.
    static func pieces(fromJSON3 data: Data) throws -> [TranscriptPiece] {
        let events = try JSONDecoder().decode(JSON3.self, from: data).events ?? []
        var pieces: [TranscriptPiece] = events.compactMap { event in
            guard let start = event.tStartMs, let segments = event.segs else { return nil }
            let text = segments.compactMap(\.utf8).joined()
                .split(whereSeparator: \.isWhitespace).joined(separator: " ")
            guard !text.isEmpty else { return nil }
            return TranscriptPiece(start: start / 1000, end: (start + (event.dDurationMs ?? 0)) / 1000, text: text)
        }
        for index in pieces.indices.dropLast() where pieces[index].end > pieces[index + 1].start {
            pieces[index].end = max(pieces[index].start, pieces[index + 1].start)
        }
        return pieces
    }
}
