import AVFoundation
import Foundation
import Testing

@testable import MeetingMindKit

@Suite("YouTube captions")
struct YouTubeCaptionsTests {
    @Test("Finds the video id in every link shape YouTube shares", arguments: [
        "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        "https://www.youtube.com/watch?feature=share&v=dQw4w9WgXcQ&t=42s",
        "youtube.com/watch?v=dQw4w9WgXcQ",
        "https://m.youtube.com/watch?v=dQw4w9WgXcQ",
        "https://youtu.be/dQw4w9WgXcQ?si=abc",
        "  youtu.be/dQw4w9WgXcQ\n",
        "https://www.youtube.com/shorts/dQw4w9WgXcQ",
        "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "https://www.youtube.com/live/dQw4w9WgXcQ?feature=shared",
        "https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ",
    ])
    func videoIDs(link: String) {
        #expect(YouTubeCaptions.videoID(from: link) == "dQw4w9WgXcQ")
    }

    @Test("Other links and malformed ids are rejected", arguments: [
        "https://vimeo.com/76979871",
        "https://www.youtube.com/@RickAstleyYT",
        "https://www.youtube.com/watch?v=short",
        "https://youtu.be/",
        "not a link",
        "https://notyoutube.com/watch?v=dQw4w9WgXcQ",
    ])
    func rejects(link: String) {
        #expect(YouTubeCaptions.videoID(from: link) == nil)
    }

    static let player = Data("""
        {"playabilityStatus":{"status":"OK"},
         "videoDetails":{"videoId":"dQw4w9WgXcQ","title":"Launch keynote"},
         "captions":{"playerCaptionsTracklistRenderer":{"captionTracks":[
           {"baseUrl":"https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en&kind=asr&fmt=srv3","languageCode":"en","kind":"asr"},
           {"baseUrl":"https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=de-DE&fmt=srv3","languageCode":"de-DE"},
           {"baseUrl":"https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en&fmt=srv3","languageCode":"en"}
         ]}}}
        """.utf8)

    @Test("Reads the title and caption tracks from the player response")
    func readsPlayer() throws {
        let (title, tracks) = try YouTubeCaptions.player(from: Self.player)
        #expect(title == "Launch keynote")
        #expect(tracks.map(\.languageCode) == ["en", "de-DE", "en"])
        #expect(tracks.map(\.isAutoGenerated) == [true, false, false])
    }

    @Test("An unplayable video says why")
    func unplayable() {
        let data = Data(#"{"playabilityStatus":{"status":"LOGIN_REQUIRED","reason":"Sign in to confirm your age"}}"#.utf8)
        #expect(throws: YouTubeCaptions.Failure.unavailable(reason: "Sign in to confirm your age")) {
            try YouTubeCaptions.player(from: data)
        }
    }

    @Test("Written captions in the reader's language win, then automatic ones, then anything")
    func picksTrack() throws {
        let tracks = try YouTubeCaptions.player(from: Self.player).tracks
        let english = YouTubeCaptions.bestTrack(tracks, preferredLanguages: ["en-GB"])
        #expect(english?.languageCode == "en" && english?.isAutoGenerated == false)
        #expect(YouTubeCaptions.bestTrack(tracks, preferredLanguages: ["de-AT", "en"])?.languageCode == "de-DE")
        let automaticOnly = tracks.filter { $0.isAutoGenerated || $0.languageCode == "de-DE" }
        #expect(YouTubeCaptions.bestTrack(automaticOnly, preferredLanguages: ["en-US"])?.isAutoGenerated == true)
        #expect(YouTubeCaptions.bestTrack(tracks, preferredLanguages: ["ja"])?.languageCode == "de-DE")
        #expect(YouTubeCaptions.bestTrack([], preferredLanguages: ["en"]) == nil)
    }

    @Test("Caption requests ask for the JSON format")
    func json3URL() throws {
        let track = try #require(YouTubeCaptions.player(from: Self.player).tracks.first)
        let items = URLComponents(url: YouTubeCaptions.json3URL(for: track), resolvingAgainstBaseURL: false)?.queryItems ?? []
        #expect(items.filter { $0.name == "fmt" }.map(\.value) == ["json3"])
        #expect(items.contains(URLQueryItem(name: "kind", value: "asr")))
    }

    @Test("Caption events become timed pieces; rolling ones stop where the next starts")
    func pieces() throws {
        let json = Data("""
            {"events":[
              {"tStartMs":0,"dDurationMs":211879,"id":1},
              {"tStartMs":320,"dDurationMs":14260,"segs":[{"utf8":"[Music]"}]},
              {"tStartMs":18790,"aAppend":1,"segs":[{"utf8":"\\n"}]},
              {"tStartMs":18800,"dDurationMs":7160,"segs":[{"utf8":"We're"},{"utf8":" no","tOffsetMs":239},{"utf8":" strangers"}]},
              {"tStartMs":21800,"dDurationMs":2000,"segs":[{"utf8":"to\\nlove."}]}
            ]}
            """.utf8)
        let pieces = try YouTubeCaptions.pieces(fromJSON3: json)
        #expect(pieces == [
            TranscriptPiece(start: 0.32, end: 14.58, text: "[Music]"),
            TranscriptPiece(start: 18.8, end: 21.8, text: "We're no strangers"),
            TranscriptPiece(start: 21.8, end: 23.8, text: "to love."),
        ])
    }

    /// Hits YouTube itself, so only on request: `YOUTUBE_LIVE=1 swift test --filter YouTube`.
    @Test("Fetches captions for a real video", .enabled(if: ProcessInfo.processInfo.environment["YOUTUBE_LIVE"] != nil))
    func live() async throws {
        let video = try await YouTubeCaptions.fetch("https://youtu.be/dQw4w9WgXcQ", preferredLanguages: ["en-US"])
        print("LIVE:", video.title, video.pieces.count, video.pieces.prefix(3))
        #expect(video.title.contains("Never Gonna Give You Up"))
        #expect(TranscriptPiece.joined(video.pieces).localizedCaseInsensitiveContains("strangers"))
    }
}

@Suite("Media import")
struct MediaImporterTests {
    let directory = FileManager.default.temporaryDirectory.appending(path: "media-import-\(UUID())")

    static func spokenAudio() throws -> URL {
        let url = FileManager.default.temporaryDirectory.appending(path: "spoken-\(UUID()).aiff")
        let say = Process()
        say.executableURL = URL(filePath: "/usr/bin/say")
        say.arguments = ["-o", url.path, "Priya will write the press release by Friday."]
        try say.run()
        say.waitUntilExit()
        return url
    }

    @Test("Audio the transcriber can read is copied as it is")
    func copiesAudio() async throws {
        let source = try Self.spokenAudio()
        defer { try? FileManager.default.removeItem(at: source); try? FileManager.default.removeItem(at: directory) }

        let result = try await MediaImporter.importMedia(from: source, into: directory)
        #expect(result.url.deletingLastPathComponent().standardizedFileURL == directory.standardizedFileURL)
        #expect(result.url.pathExtension == "aiff")
        #expect(result.duration > 1)
        #expect(FileManager.default.fileExists(atPath: source.path))
    }

    @Test("A video's sound track is written out as m4a")
    func extractsVideoAudio() async throws {
        let audio = try Self.spokenAudio()
        let movie = try await Self.movie(withAudio: audio)
        defer { [audio, movie, directory].forEach { try? FileManager.default.removeItem(at: $0) } }

        let result = try await MediaImporter.importMedia(from: movie, into: directory)
        #expect(result.url.pathExtension == "m4a")
        #expect(result.duration > 1)
        let tracks = try await AVURLAsset(url: result.url).loadTracks(withMediaType: .video)
        #expect(tracks.isEmpty)
        #expect(try AVAudioFile(forReading: result.url).length > 0)
    }

    @Test("A file with no sound is refused")
    func refusesSilentFile() async throws {
        let text = FileManager.default.temporaryDirectory.appending(path: "notes-\(UUID()).txt")
        try Data("hello".utf8).write(to: text)
        defer { try? FileManager.default.removeItem(at: text); try? FileManager.default.removeItem(at: directory) }
        await #expect(throws: MediaImporter.Failure.unreadable) {
            try await MediaImporter.importMedia(from: text, into: directory)
        }
    }

    /// A small .mov: two black frames over the given audio, the shape of a phone video.
    static func movie(withAudio audio: URL) async throws -> URL {
        let url = FileManager.default.temporaryDirectory.appending(path: "clip-\(UUID()).mov")
        let format = try AVAudioFile(forReading: audio).fileFormat
        let writer = try AVAssetWriter(outputURL: url, fileType: .mov)
        let video = AVAssetWriterInput(mediaType: .video, outputSettings: [
            AVVideoCodecKey: AVVideoCodecType.h264, AVVideoWidthKey: 64, AVVideoHeightKey: 64,
        ])
        let adaptor = AVAssetWriterInputPixelBufferAdaptor(assetWriterInput: video, sourcePixelBufferAttributes: nil)
        let sound = AVAssetWriterInput(mediaType: .audio, outputSettings: [
            AVFormatIDKey: kAudioFormatMPEG4AAC, AVSampleRateKey: format.sampleRate, AVNumberOfChannelsKey: 1,
        ])
        writer.add(video)
        writer.add(sound)

        let asset = AVURLAsset(url: audio)
        let reader = try AVAssetReader(asset: asset)
        let output = AVAssetReaderTrackOutput(track: try await asset.loadTracks(withMediaType: .audio)[0],
                                              outputSettings: [AVFormatIDKey: kAudioFormatLinearPCM])
        reader.add(output)
        reader.startReading()
        writer.startWriting()
        writer.startSession(atSourceTime: .zero)

        for second in 0..<2 {
            var buffer: CVPixelBuffer?
            CVPixelBufferCreate(nil, 64, 64, kCVPixelFormatType_32ARGB, nil, &buffer)
            while !video.isReadyForMoreMediaData { try await Task.sleep(for: .milliseconds(5)) }
            adaptor.append(try #require(buffer), withPresentationTime: CMTime(seconds: Double(second), preferredTimescale: 600))
        }
        video.markAsFinished()
        while let sample = output.copyNextSampleBuffer() {
            while !sound.isReadyForMoreMediaData { try await Task.sleep(for: .milliseconds(5)) }
            sound.append(sample)
        }
        sound.markAsFinished()
        await writer.finishWriting()
        try #require(writer.status == .completed, "\(String(describing: writer.error))")
        return url
    }
}
